# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/vivid64"
  config.vm.hostname = "slave1"
  config.vm.network "private_network", ip:"10.0.11.31"
  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
  end

                        
  config.vm.provision :chef_solo do |chef|
		chef.version = "12.3.0"
		chef.cookbooks_path = '../cookbooks'
		chef.add_recipe "dbsetup::slave"
		chef.add_recipe "dbsetup::slave1"
  end
end
