#<% require 'kitchen-sync' %>
---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %> 
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  flavor_id: <%= ENV['EC2_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-5.8
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-5-8-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-6.5
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-6-5-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

- name: centos-7.0
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: centos-7-0-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

# - name: redhat-6.5
#   driver_plugin: ec2
#   driver_config:
#     image_id: ami-8d756fe4
#     username: ec2-user
#     ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: amazon-2014.09
  driver_plugin: ec2
  driver_config:
    image_id: ami-9a6ed3f2
    username: ec2-user
    ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

- name: fedora-21
  driver_plugin: digital_ocean
  driver_config:
    size: 2gb
    image: fedora-21-x64
    region: <%= ENV['DIGITALOCEAN_REGION'] %>
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEYS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

suites:
- name: default
  run_list:
  - recipe[yum::default]
  attributes: {}
