#<% require 'kitchen-sync' %>
---
driver:
  name: docker

provisioner:
  name: chef_zero
  # require_chef_omnibus: 11.16.4
  # require_chef_omnibus: 12.0.3
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
  driver_config:
    image: centos
    platform: rhel

- name: centos-7.0
  driver_config:
    image: centos
    platform: rhel

suites:
- name: default
  run_list:
  - recipe[yum::default]
  attributes: {}
